world-border:
  enabled: true
  center-x: 0
  center-z: 0
  size: 5000

scoreboard:
  enabled: true
  title: "&6&lHCF"
  lines:
    - "&7&m----------------"
    - "&fFaction: &e%faction%"
    - "&fDTR: &e%dtr%"
    - "&fBalance: &e$%balance%"
    - "&fOnline: &e%online%"
    - "&7&m----------------"

airdrops:
  enabled: true
  announce-chat: false
  bossbar: true
  interval-minutes: 30
  lifetime-seconds: 300
  random-radius: 2450

iron-golems:
  enabled: true

villagers:
  enabled: true

combat-tag:
  enabled: true
  seconds: 30

deathban:
  enabled: true
  minutes: 30